packages:
  - packages/*
  - examples/*
  - docs

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - sharp

overrides:
  '@modelcontextprotocol/sdk@<1.24.0': '>=1.24.0'
  ai@<5.0.52: '>=5.0.52'
  astro@<5.15.8: '>=5.15.8'
  astro@<5.15.9: '>=5.15.9'
  astro@<=5.15.6: '>=5.15.8'
  astro@>=2.16.0 <5.15.5: '>=5.15.5'
  astro@>=5.2.0 <5.15.6: '>=5.15.6'
  body-parser@>=2.2.0 <2.2.1: '>=2.2.1'
  glob@>=10.2.0 <10.5.0: '>=10.5.0'
  glob@>=11.0.0 <11.1.0: '>=11.1.0'
  js-yaml@<3.14.2: '>=3.14.2'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  jws@<3.2.3: '>=3.2.3'
  mdast-util-to-hast@>=13.0.0 <13.2.1: '>=13.2.1'
  next@>=15.4.0-canary.0 <15.4.8: '>=15.4.8'
  tar@=7.5.1: '>=7.5.2'
  validator@<13.15.20: '>=13.15.20'
  validator@<13.15.22: '>=13.15.22'

publishBranch: main
