"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const node_fs_1 = require("node:fs");
const node_path_1 = require("node:path");
const node_process_1 = require("node:process");
const packageJson = JSON.parse((0, node_fs_1.readFileSync)((0, node_path_1.resolve)((0, node_process_1.cwd)(), 'package.json'), 'utf-8'));
const dependencies = Object.entries(packageJson.dependencies);
const openaiDependencies = dependencies.filter(([name]) => name.startsWith('@openai/') || name === 'openai');
const versions = {
    [packageJson.name]: packageJson.version,
    ...Object.fromEntries(openaiDependencies.map(([name, version]) => [name, version])),
};
const METADATA = {
    name: packageJson.name,
    version: packageJson.version,
    versions: versions,
};
const output = `
// This file is automatically generated

export const METADATA = ${JSON.stringify(METADATA, null, 2)};

export default METADATA;
`;
(0, node_fs_1.writeFileSync)((0, node_path_1.resolve)((0, node_process_1.cwd)(), 'src/metadata.ts'), output, 'utf-8');
